### ISSUE TITLE
Add `diff-hl` to the list

### ISSUE THREAD

**Issue by kaushalmodi** [tarsius/git-elisp#1]
This is an amazing package: https://github.com/dgutov/diff-hl

I found it better than `git-gutter.el` (and family) of packages.

**Comment by tarsius** [comment]
I knew about that one! Don't no why I forgot to list it.

Could you please open a pr, I am quite swamped. (Or we can also let it sit for a while).

> I found it better than `git-gutter.el` (and family) of packages.

One of its advantages is that it *doesn't* have a family! I find the whole fork situation of git-gutter(+) quite frustrating.

**Comment by tarsius** [comment]
Done.

**Comment by ReneFroger** [comment]
Thanks for your contributions. Do you mind that I added nearly all of them to [emacs.zeef.com](http://emacs.zeef.com)?
